### ISSUE TITLE
README.md needs an update by listing all the project names.

### ISSUE THREAD

**Issue by Sudhi27Krishna** [Sudhi27Krishna/Web-Development#2]
@alimon777 Kindly do the needful.

**Comment by mohameddjebloun** [comment]
If you mean just writing the names of all the follders in this repo(projects) or of all your repos then I can do that for you but if you also want descriptions for your projects then I'm afraid I can't help

**Comment by Sudhi27Krishna** [comment]
Sure I'll assign it to you. Just write the list of name of projects avoid the HTML folder. No need to add descriptions.
